FROM node:16-alpine AS builder
# Add ARG lines for environment variables
ARG MONGODB_URI
ARG NOREPLY_EMAIL
ARG NOREPLY_PASS
ARG URL
ARG NEXTAUTH_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG OPENAI_API_KEY
ARG GOOGLE_API_KEY
ARG CUSTOM_SEARCH_ENGINE_ID
ARG NEXTAUTH_URL
ARG JWT_SECRET
ARG PUPPETEER_EXECUTABLE_PATH
ARG PUPPETEER_SKIP_CHROMIUM_DOWNLOAD

WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

FROM node:16-alpine AS final

# --- START ---

RUN apk add --no-cache chromium ca-certificates
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium-browser

# --- END ---

# Add ENV lines to set environment variables for the runtime
ENV MONGODB_URI=$MONGODB_URI
ENV NOREPLY_EMAIL=$NOREPLY_EMAIL
ENV NOREPLY_PASS=$NOREPLY_PASS
ENV URL=$URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV GOOGLE_API_KEY=$GOOGLE_API_KEY
ENV CUSTOM_SEARCH_ENGINE_ID=$CUSTOM_SEARCH_ENGINE_ID
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV JWT_SECRET=$JWT_SECRET
ENV PUPPETEER_EXECUTABLE_PATH=$PUPPETEER_EXECUTABLE_PATH
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=$PUPPETEER_SKIP_CHROMIUM_DOWNLOAD

WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/.env.example .
COPY package.json .
COPY package-lock.json .
RUN npm ci --only=production
EXPOSE 8080
CMD ["npm", "start"]
